# Generated by Django 2.1.4 on 2018-12-14 21:22

from django.db import migrations
import markupfield_helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('system_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationrecord',
            name='documentation',
            field=markupfield_helpers.helpers.MarkupField(blank=True, help_text='Document how to perform a task.', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=markupfield_helpers.helpers.MarkupField(blank=True, help_text='Enter a description of the system maintenance performed.', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='problems',
            field=markupfield_helpers.helpers.MarkupField(blank=True, help_text='Describe problems that arose during system maintenance.', null=True, rendered_field=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='procedure',
            field=markupfield_helpers.helpers.MarkupField(blank=True, help_text='Enter details of how the system maintenance was performed.', null=True, rendered_field=True),
        ),
    ]
